name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - '**/*.php'
      - 'composer.json'
      - 'composer.lock'
      - '.github/workflows/run-tests.yml'
  workflow_dispatch:

jobs:
  tests:
    name: Tests PHP ${{ matrix.php }} · Laravel ${{ matrix.laravel }} · ${{ matrix.stability }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3', '8.4']
        laravel: ['11', '12']
        stability: ['prefer-stable', 'prefer-lowest']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, dom, json, ctype, openssl, pdo, pdo_sqlite, sqlite3
          coverage: none
          tools: composer:v2

      - name: Composer cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache/files
            ~/.cache/composer
          key: composer-${{ runner.os }}-${{ matrix.php }}-${{ matrix.laravel }}-${{ matrix.stability }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php }}-${{ matrix.laravel }}-${{ matrix.stability }}-
            composer-${{ runner.os }}-

      - name: Configure stability
        run: |
          if [ "${{ matrix.stability }}" = "prefer-lowest" ]; then
            echo "COMPOSER_FLAGS=--prefer-lowest --prefer-dist" >> $GITHUB_ENV
          else
            echo "COMPOSER_FLAGS=--prefer-dist" >> $GITHUB_ENV
          fi

      - name: Install dependencies (lock-resolve for Laravel ${{ matrix.laravel }})
        run: |
          composer update --no-interaction --no-progress $COMPOSER_FLAGS \
            --with="illuminate/console:^${{ matrix.laravel }}" \
            --with="illuminate/contracts:^${{ matrix.laravel }}" \
            --with="illuminate/database:^${{ matrix.laravel }}" \
            --with="illuminate/http:^${{ matrix.laravel }}" \
            --with="illuminate/support:^${{ matrix.laravel }}"

      - name: Run tests (Pest)
        run: |
          vendor/bin/pest -q
